# -*- coding: utf-8 -*-
"""Cleaned_Question_Bank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zc1H3GKlOE4oTj0_JPR0V_aWE2z2MJ_P
"""

import pandas as pd

# Step 1: Reading messy dataset

df = pd.read_excel("Dataset/Part_3_Data_Cleaning - question_bank_messy_large.xlsx")

# Step 2: Pre-Viewing the dataset
df.head()

# Step 3 : Checkinging for Missing Values
df.isnull().sum()

# Step 3: Standardizing subject
df["subject"] = df["subject"].str.strip()

df["subject"] = df["subject"].replace({
    "MATH": "Mathematics",
    "math": "Mathematics"
})

# Step 4: Standardizing grade
df["grade"] = df["grade"].replace({
    "Six": 6,
    "VII": 7
})

df["grade"] = pd.to_numeric(df["grade"], errors="coerce")

# Step 5: Standardizing competency
df["competency"] = df["competency"].str.strip().str.title()

# Step 6: Standardizing difficulty
df["difficulty"] = df["difficulty"].str.strip()

df["difficulty"] = df["difficulty"].replace({
    "E": "easy",
    "Easy": "easy",
    "EASY": "easy",
    "M": "medium",
    "MED": "medium",
    "Hard": "hard",
    "H": "hard"
})

# Step 7: Standardizing question type
df["question_type"] = df["question_type"].str.strip()

df["question_type"] = df["question_type"].replace({
    "mcq": "MCQ"
})

# Step 8: Standardizing marks
df["marks"] = df["marks"].replace({
    "two": 2
})

df["marks"] = pd.to_numeric(df["marks"], errors="coerce")

# Step 9: Cleaning question text
df["question_text"] = df["question_text"].str.strip()

# Step 10: Handling missing values
df = df.dropna(subset=["question_text"])

df["difficulty"] = df["difficulty"].fillna("unknown")
df["question_type"] = df["question_type"].fillna("Unknown")
df["created_by"] = df["created_by"].fillna("Unknown")

# Step 11: Removing duplicate questions
df = df.drop_duplicates(subset=["question_text"])

# Step 12: Converting date column
df["last_used_date"] = pd.to_datetime(
    df["last_used_date"],
    errors="coerce"
)

# Step 13 : Re-viewing the dataset
df.head()

# Step 14 : Rechecking the Missing Values

print(df.isnull().sum())
#As Still Missing Values occured, we need to further handle missing values

# Step 15 : Finding what values exists in Grade Column

print(df["grade"].value_counts(dropna=False))

# Step 16 : Removing Missing Grade Column Values

df = df.dropna(subset=["grade"])

# Step 17 : Checking Missing Values for Grade

print(df.isnull().sum())

# Step 18 : Finding what values exists in Grade Column

print(df["marks"].value_counts(dropna=False))

# Step 19 : Removing Missing Grade Column Values

df["marks"] = df["marks"].fillna(df["marks"].median())

# Step 20 : Checking Missing Values for Grade

print(df.isnull().sum())

# Step 21 : Finding what values exists in Grade Column (Leaving it as it is, as it is not an important column)

print(df["last_used_date"].value_counts(dropna=False))

# Step 22 : Finding what values exists in Difficulty Column

print(df["difficulty"].value_counts(dropna=False))

# Step 23 : Standardized and Retained the Unknown Difficulty Column Values

df["difficulty"] = df["difficulty"].fillna("unknown")

# Step 24 : Finding what values exists in Created_by Column

print(df["created_by"].value_counts(dropna=False))

# Step 25 : Standardized and Retained the Unknown Difficulty Column Values

df["created_by"] = df["created_by"].fillna("Unknown")

# Step 26 : Checking duplicate values for question_id and question_text fields

print("Duplicate Question IDs:",
      df.duplicated(subset=["question_id"]).sum())

print("Duplicate Question Texts:",
      df.duplicated(subset=["question_text"]).sum())

# Step 27 : Printing all the duplicate vales in dataset

print("Remaining Duplicates:", df.duplicated().sum())

print("Cleaned dataset exported successfully.")

# Step 28: Export cleaned dataset

df.to_csv("Dataset/cleaned_question_bank.csv", index=False)