# -*- coding: utf-8 -*-
"""Peepul_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdd05iGkbM-Z2pprnlxQhJBwJXGTID69
"""

import pandas as pd

# Step 1: Read the question bank dataset

df = pd.read_excel("Dataset/Part_1_2_question_bank - question_bank_clean 1.xlsx")

# Pre-viewing the dataset

df.head()

# Step 2: Standardizing the important columns

df["difficulty"] = df["difficulty"].str.lower().str.strip()
df["subject"] = df["subject"].str.strip()
df["competency"] = df["competency"].str.strip()

# Step 3 :Blueprint configuration

blueprint = {
    "grade": 6,
    "total_questions": 10,
    "difficulty_distribution": {
        "easy": 4,
        "medium": 4,
        "hard": 2
    }
}

# Step 4 : Function to generate question paper
def generate_question_paper(df, blueprint):

    # Getting blueprint values
    grade = blueprint["grade"]
    total_questions = blueprint["total_questions"]
    difficulty_distribution = blueprint["difficulty_distribution"]

    # Filtering questions based on grade
    filtered_df = df[df["grade"] == grade]

    selected_questions = []

    # Selecting questions difficulty-wise
    for difficulty, count in difficulty_distribution.items():

        questions = filtered_df[
            filtered_df["difficulty"] == difficulty
        ]

        sampled_questions = questions.sample(n=count, replace=False)

        selected_questions.append(sampled_questions)

    # Combining selected questions
    question_paper = pd.concat(selected_questions)

    # Adding question numbers
    question_paper = question_paper.reset_index(drop=True)
    question_paper.insert(0, "Question_No", range(1, len(question_paper) + 1))

    # Checking total questions
    if len(question_paper) == total_questions:
        print("Question paper generated successfully.")
    else:
        print("Question count does not match blueprint.")

    # Exporting selected questions
    question_paper.to_csv("generated_question_paper.csv", index=False)

    return question_paper

# Step 5 : Generate question paper

question_paper = generate_question_paper(df, blueprint)

# Step 6 : Display selected questions
print(question_paper)

print("\nQuestion Paper Summary")

print("Total Questions:",
      len(question_paper))

print("\nDifficulty Distribution")

print(
    question_paper["difficulty"]
    .value_counts()
)

print("\nCompetency-wise Weightage")

print(
    question_paper["competency"]
    .value_counts()
)